# stage1 - build
FROM node:12.16.1-alpine3.9 as build
WORKDIR /app
COPY ["./package.json","./package-lock.json", "./"]
RUN npm install
COPY ./public ./public
COPY ./src ./src
RUN CI=true npm run test
RUN npm run build

# stage 2 - nginx build image
FROM node:12.16.1-alpine3.9
COPY --from=build /app/build /app/build
WORKDIR /app
RUN npm install -g serve
EXPOSE 5000
CMD ["serve", "-s", "build"]