# stage1 - build
FROM node:12.16.1-alpine3.9 as build
WORKDIR /app
COPY ["./package.json","./package-lock.json", "./"]
RUN npm install
COPY ./public ./public
COPY ./src ./src
RUN CI=true npm run test
RUN npm run build

# stage 2 - nginx build image
FROM nginx:1.17.8-alpine
COPY --from=build /app/build /usr/share/nginx/html
RUN rm /etc/nginx/conf.d/default.conf
COPY nginx/nginx.conf /etc/nginx/conf.d
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]